In [189]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [190]:
np.power(2 * np.ones(20), np.arange(1, 21)) * [1 / np.arange(1, 21)]

array([[2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
        6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
        5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
        6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
        7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04]])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [191]:
np.sum(((np.ones(6) * 0.1) ** (3 * np.arange(6))) * ((np.ones(6) * 0.2) ** (4 * np.arange(6))))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [192]:
A = np.zeros((8,8), dtype=int)

A[1::2,::2] = 1
A[::2,1::2] = 1

print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [64]:
X = np.random.random((5, 2))

In [115]:
X1 = np.array([np.sqrt(X[:, 0] ** 2 + X[:, 1] ** 2), np.arctan(X[:, 1], X[:, 0])]).T
X, '---------', X1

(array([[0.56646741, 0.63599587],
        [0.20018417, 0.20290178],
        [0.40199762, 0.42514991],
        [0.46057394, 0.4961638 ],
        [0.17307299, 0.17482204],
        [0.24421009, 0.24918355],
        [0.58040328, 0.65574499],
        [0.20226708, 0.20507136],
        [0.72002812, 0.87711766],
        [0.7340331 , 0.90220699]]),
 '---------',
 array([[0.91914942, 0.56646741],
        [0.38509177, 0.20018417],
        [0.44157598, 0.40199762],
        [0.9359265 , 0.46057394],
        [0.77175728, 0.17307299],
        [0.5190565 , 0.24421009],
        [0.74079355, 0.58040328],
        [0.63794943, 0.20226708],
        [1.07834178, 0.72002812],
        [1.14213661, 0.7340331 ]]))

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [110]:
X = np.random.random((10, 10))
X

array([[0.13711626, 0.41410264, 0.69576406, 0.11908892, 0.58911935,
        0.00621624, 0.58638626, 0.41582045, 0.77355183, 0.27747938],
       [0.44396315, 0.9464265 , 0.31643089, 0.60194774, 0.09605937,
        0.59492532, 0.6254692 , 0.34133784, 0.21633023, 0.89687329],
       [0.55694315, 0.02604665, 0.9824774 , 0.45052706, 0.76982934,
        0.54632151, 0.72385961, 0.43584285, 0.90913785, 0.14592419],
       [0.57828512, 0.93669885, 0.76498894, 0.44674607, 0.50160657,
        0.45088815, 0.2246755 , 0.95433474, 0.2262075 , 0.55415372],
       [0.08297523, 0.39758253, 0.76579526, 0.79771223, 0.11248254,
        0.84890829, 0.71532127, 0.59706767, 0.45821644, 0.12918372],
       [0.6555671 , 0.97966661, 0.36832084, 0.96497534, 0.74938813,
        0.71925671, 0.86819634, 0.38876992, 0.51992649, 0.67158016],
       [0.14463777, 0.32217073, 0.91717839, 0.38150308, 0.92079822,
        0.07958235, 0.94672972, 0.70740392, 0.0222762 , 0.26760889],
       [0.16494802, 0.00659676, 0.9588227

In [111]:
np.unravel_index(np.argmax(X), X.shape)

(8, 8)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [121]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
X, '-----------', y

(array([[0.07288331, 0.91257461],
        [0.44685364, 0.73327327],
        [0.35144297, 0.92302139],
        [0.02016297, 0.28211606],
        [0.76923405, 0.84160094],
        [0.22683661, 0.08670328],
        [0.01157543, 0.07465322],
        [0.65361195, 0.70385517],
        [0.39979846, 0.00655392],
        [0.76764527, 0.52753947]]),
 '-----------',
 array([[0.38582199, 0.27597119]]))

In [135]:
d = np.linalg.norm(X - y, axis=1)
X[np.argmin(d), :]

array([0.22683661, 0.08670328])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [176]:
x = 5 * np.random.random(7) - 2
x

array([-0.20290203,  0.85242781, -0.46821968,  2.07500384,  2.5310068 ,
        0.31661837,  0.18073459])

In [177]:
E1 = x < 0
E2 = (0 <= x) & (x <= 2)
E3 = x >= 2

x[E1] = x[E1] ** 2 + 2 * x[E1] + 6
x[E2] = x[E2] + 6
x[E3] = x[E3] ** 2 + 4 * x[E3] - 4

x

array([ 5.63536517,  6.85242781,  5.2827903 ,  8.60565633, 12.53002265,
        6.31661837,  6.18073459])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [180]:
X = np.random.random((10, 10))
X

array([[0.45668964, 0.1018795 , 0.06117318, 0.49582247, 0.43752882,
        0.56903665, 0.59575705, 0.65423989, 0.09499091, 0.0755501 ],
       [0.12888246, 0.29185106, 0.13195981, 0.63746156, 0.21178783,
        0.75043741, 0.54128447, 0.59655283, 0.77326499, 0.12848669],
       [0.61747214, 0.10376972, 0.08128547, 0.4052686 , 0.78692546,
        0.76847138, 0.70628836, 0.84552383, 0.39013029, 0.94792424],
       [0.74834061, 0.28236998, 0.40651308, 0.52771494, 0.10937965,
        0.1034094 , 0.62160863, 0.97662136, 0.6128411 , 0.79671374],
       [0.46656525, 0.03553264, 0.79711063, 0.15560808, 0.1420087 ,
        0.22641032, 0.33927983, 0.78278378, 0.90306414, 0.52387309],
       [0.85198809, 0.01322993, 0.01248989, 0.62643252, 0.43827463,
        0.46937043, 0.9185639 , 0.96607399, 0.1701784 , 0.97217449],
       [0.93110914, 0.25257386, 0.01277814, 0.0484139 , 0.31885727,
        0.12282417, 0.01885927, 0.36463314, 0.11681163, 0.32210509],
       [0.49615346, 0.56454327, 0.4117387

In [183]:
X = X - np.mean(X, axis=1).reshape(10, 1)
np.mean(X, axis=1)

array([ 5.55111512e-18,  1.11022302e-17,  1.11022302e-17,  0.00000000e+00,
        4.85722573e-18,  1.11022302e-17, -1.11022302e-17,  4.16333634e-18,
       -1.66533454e-17,  1.66533454e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [193]:
X = np.random.normal(loc=5, scale=2., size=1000)

In [198]:
mean = (1/np.size(X)) * np.sum(X)
variance = (1/np.size(X)) * np.sum((X - mean)**2)

mean, variance

(4.9380824034994, 4.1564097206458355)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [207]:
X = np.array(5 * [np.arange(5)])
X += X.T
X %= 5
X

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [259]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 4, 0, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [267]:
def another_sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    
    A = np.stack(c * [np.cumsum(x)], axis=0)
    val = s * np.random.random((c,1))
    res = list(np.argmax(A >= val, axis=1))
    return res
    
            
another_sample([50, 3, 1, 7, 20], 5)    

[0, 4, 0, 0, 0]